import { Inter } from "next/font/google";
import "./globals.css";
import { ToastConfig } from "./toast-config";
import { ThemeProvider } from "next-themes";
import ThemeSwitcher from "@/components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>


        <ThemeProvider
          attribute="class"
          defaultTheme={"light"}
          enableColorScheme={false}
        >

          <ToastConfig />
      
          <ThemeSwitcher />
          {children}

        </ThemeProvider>





      </body>
    </html>
  );
}
